In [43]:
import numpy as np
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [44]:
def mae(y_predicted,y_true):
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=abs(yt-yp)
    mean=total_error/len(y_true)
    return mean
mae(y_predicted,y_true)

0.5

In [45]:
np.mean(np.abs(y_true- y_predicted))

0.5

In [46]:
np.log([0.000000000000000001])

array([-41.44653167])

In [47]:
epsilon=1e-15

In [48]:
y_predicted

array([1, 1, 0, 0, 1])

In [54]:
y_predicted_new=[ max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [55]:
y_predicted_new=[ min(i,1-epsilon)  for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [57]:
y_predicted_new=np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [59]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


17.2696280766844